name: swe_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - netcdf4
  - scipy
  - matplotlib
  - cartopy
  - numpy
  - geopandas
  - pandas
  - fsspec
  - s3fs
  - requests
